apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: krill
  annotations:
    run.googleapis.com/launch-stage: BETA
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
        autoscaling.knative.dev/maxScale: "1"
        run.googleapis.com/execution-environment: gen2
        run.googleapis.com/startup-cpu-boost: "true"
    spec:
      serviceAccountName: hy-408@fleet-anagram-244304.iam.gserviceaccount.com
      timeoutSeconds: 300
      containers:
        - image: us-central1-docker.pkg.dev/fleet-anagram-244304/krill/krill:latest
          resources:
            limits:
              cpu: "1"
              memory: 2Gi
          env:
            - name: TELEGRAM_BOT_TOKEN
              value: __TELEGRAM_BOT_TOKEN__
            - name: OPENAI_API_KEY
              value: __OPENAI_API_KEY__
            - name: GEMINI_API_KEY
              value: __GEMINI_API_KEY__
            - name: GH_PAT
              value: __GH_PAT__
            - name: KRILL_DATA_DIR
              value: /data
          volumeMounts:
            - name: krill-data
              mountPath: /data
      volumes:
        - name: krill-data
          csi:
            driver: gcsfuse.run.googleapis.com
            volumeAttributes:
              bucketName: krill-data
  traffic:
    - percent: 100
      latestRevision: true
