module Core

include("types.jl")
include("message_hub.jl")
include("manager.jl")
include("dedup.jl")
include("channels.jl")
include("sessions.jl")
include("memory.jl")
include("echo.jl")
include("session_consumer.jl")
include("tools.jl")
include("skills.jl")
include("prompt_context.jl")
include("cron.jl")
include("builtin_tools/builtin_tools.jl")
include("mcp.jl")
include("llm/llm.jl")
include("memory_consolidation.jl")
include("subagent.jl")
include("agent.jl")
include("durable_queue.jl")

using .Types: ContentPart,
    TextPart,
    BinaryPart,
    ToolCallPart,
    ToolResultPart,
    DeliveryPolicy,
    ErrorEnvelope,
    MCPConnectionError,
    MemoryConsolidationError,
    InboundMessage,
    OutboundMessage,
    ToolCallEvent,
    ToolResultEvent,
    message_text

using .MessageHub: MessageHubState,
    publish_inbound!,
    publish_outbound!,
    try_publish_inbound!,
    try_publish_outbound!,
    take_inbound!,
    take_outbound!,
    try_take_inbound!,
    try_take_outbound!

using .ChannelManager: ChannelManagerState,
    DispatchEvent,
    register_sender!,
    start_dispatch!,
    stop_dispatch!,
    dispatch_stats,
    dead_letters,
    flush_dead_letters!

using .Dedup: BoundedDedup,
    seen!,
    has_seen

using .ChannelInterface: AbstractChannel,
    channel_name,
    make_sender,
    normalize,
    start_channel!,
    stop_channel!,
    send_typing,
    send_direct,
    ChannelState,
    register_channel!,
    make_inbound_handler

using .Sessions: SessionStore,
    TurnRecord,
    get_session_lock!,
    load_history,
    append_turn!,
    save_history,
    session_dir,
    sanitize_session_key

using .Memory: MemoryStore,
    MemoryState,
    memory_dir,
    memory_path,
    history_path,
    memory_state_path,
    load_memory,
    save_memory!,
    append_history!,
    load_memory_state,
    save_memory_state!

using .Echo: run_echo_loop!

using .SessionConsumer:
    run_session_loop!,
    echo_processor,
    SessionCancelScope,
    request_cancel!,
    is_cancelled,
    clear_cancel!

using .Tools: AbstractToolDef,
    ToolDef,
    ToolRegistry,
    ToolNotFoundError,
    ToolValidationError,
    ToolExecutionError,
    register_tool!,
    unregister_tool!,
    get_tool,
    has_tool,
    tool_names,
    tools_schema,
    dispatch_tool,
    @tool

using .Skills: SkillDef,
    discover_skills,
    read_skill,
    skills_summary,
    load_always_skills,
    register_read_skill_tool!

using .PromptContext: BootstrapDoc,
    DEFAULT_BOOTSTRAP_DOCS,
    RUNTIME_CONTEXT_MARKER,
    TOOL_OUTPUT_SAFETY_NOTICE,
    load_bootstrap_docs,
    render_runtime_metadata,
    compose_instructions,
    make_prompt_builder

using .BuiltinTools: register_builtin_tools!, register_cron_tools!, set_cron_context!

using .MCP: MCPServer,
    AbstractMCPClient,
    MCPStdioClient,
    MCPHTTPClient,
    MCPConnectionSet,
    connect,
    connect!,
    close!,
    list_tools,
    call_tool,
    mcp_wrapped_tool_name,
    register_mcp_tools!,
    connect_mcp_servers!

using .LLM: AbstractLLMProvider,
    OpenAIProvider,
    GeminiProvider,
    GeminiOpenAICompatProvider,
    OpenAIAPIError,
    LLMToolCall,
    LLMUsage,
    LLMResponse,
    build_context,
    chat_completion,
    make_llm_processor

using .MemoryConsolidation: MemoryConsolidatorConfig,
    estimate_turn_tokens,
    estimate_turns_tokens,
    consolidate_session_memory!,
    make_memory_consolidator

using .Subagent: SubagentTask,
    SubagentManager,
    spawn_subagent!,
    cancel_subagents!,
    list_subagents,
    subagent_count,
    register_spawn_tools!,
    set_spawn_context!

using .AgentModule: RetryConfig, AgentHooks, Agent,
    MemoryConfig, BuiltinToolsConfig, SkillsConfig,
    ClaudeCodeConfig, CodexConfig, PromptContextConfig, SubagentConfig

using .Cron: CronJob, CronService,
    add_job!, remove_job!, list_jobs, get_job,
    is_due, parse_schedule, parse_cron,
    save_jobs!, load_jobs!

using .DurableQueue: DurableQueueState,
    enqueue!,
    ack!,
    replay,
    compact!,
    queue_stats

export Types,
    MessageHub,
    ChannelManager,
    Dedup,
    ChannelInterface,
    AbstractChannel,
    channel_name,
    make_sender,
    normalize,
    start_channel!,
    stop_channel!,
    send_typing,
    send_direct,
    ChannelState,
    register_channel!,
    make_inbound_handler,
    Sessions,
    Memory,
    Echo,
    SessionConsumer,
    Tools,
    Skills,
    PromptContext,
    BuiltinTools,
    MCP,
    LLM,
    MemoryConsolidation,
    Subagent,
    Cron,
    SubagentTask,
    SubagentManager,
    spawn_subagent!,
    cancel_subagents!,
    list_subagents,
    subagent_count,
    register_spawn_tools!,
    set_spawn_context!,
    ContentPart,
    TextPart,
    BinaryPart,
    ToolCallPart,
    ToolResultPart,
    DeliveryPolicy,
    ErrorEnvelope,
    MCPConnectionError,
    MemoryConsolidationError,
    InboundMessage,
    OutboundMessage,
    ToolCallEvent,
    ToolResultEvent,
    message_text,
    MessageHubState,
    publish_inbound!,
    publish_outbound!,
    try_publish_inbound!,
    try_publish_outbound!,
    take_inbound!,
    take_outbound!,
    try_take_inbound!,
    try_take_outbound!,
    ChannelManagerState,
    DispatchEvent,
    register_sender!,
    start_dispatch!,
    stop_dispatch!,
    dispatch_stats,
    dead_letters,
    flush_dead_letters!,
    BoundedDedup,
    seen!,
    has_seen,
    SessionStore,
    TurnRecord,
    get_session_lock!,
    load_history,
    append_turn!,
    save_history,
    session_dir,
    sanitize_session_key,
    MemoryStore,
    MemoryState,
    memory_dir,
    memory_path,
    history_path,
    memory_state_path,
    load_memory,
    save_memory!,
    append_history!,
    load_memory_state,
    save_memory_state!,
    run_echo_loop!,
    run_session_loop!,
    echo_processor,
    SessionCancelScope,
    request_cancel!,
    is_cancelled,
    clear_cancel!,
    AbstractToolDef,
    ToolDef,
    ToolRegistry,
    ToolNotFoundError,
    ToolValidationError,
    ToolExecutionError,
    register_tool!,
    unregister_tool!,
    get_tool,
    has_tool,
    tool_names,
    tools_schema,
    dispatch_tool,
    @tool,
    SkillDef,
    discover_skills,
    read_skill,
    skills_summary,
    load_always_skills,
    register_read_skill_tool!,
    BootstrapDoc,
    DEFAULT_BOOTSTRAP_DOCS,
    RUNTIME_CONTEXT_MARKER,
    TOOL_OUTPUT_SAFETY_NOTICE,
    load_bootstrap_docs,
    render_runtime_metadata,
    compose_instructions,
    make_prompt_builder,
    register_builtin_tools!,
    register_cron_tools!,
    set_cron_context!,
    MCPServer,
    AbstractMCPClient,
    MCPStdioClient,
    MCPHTTPClient,
    MCPConnectionSet,
    connect,
    connect!,
    close!,
    list_tools,
    call_tool,
    mcp_wrapped_tool_name,
    register_mcp_tools!,
    connect_mcp_servers!,
    AbstractLLMProvider,
    OpenAIProvider,
    GeminiProvider,
    GeminiOpenAICompatProvider,
    OpenAIAPIError,
    LLMToolCall,
    LLMUsage,
    LLMResponse,
    build_context,
    chat_completion,
    make_llm_processor,
    MemoryConsolidatorConfig,
    estimate_turn_tokens,
    estimate_turns_tokens,
    consolidate_session_memory!,
    make_memory_consolidator,
    CronJob,
    CronService,
    add_job!,
    remove_job!,
    list_jobs,
    get_job,
    is_due,
    parse_schedule,
    parse_cron,
    save_jobs!,
    load_jobs!,
    DurableQueue,
    DurableQueueState,
    enqueue!,
    ack!,
    replay,
    compact!,
    queue_stats,
    AgentModule,
    RetryConfig,
    AgentHooks,
    Agent,
    MemoryConfig,
    BuiltinToolsConfig,
    SkillsConfig,
    ClaudeCodeConfig,
    CodexConfig,
    PromptContextConfig,
    SubagentConfig

end
